name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev = "npx prisma migrate deploy && npm exec react-router dev"

# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "823c4ac0ed0c9aa9aec7a44543fc782e"
name = "WhatSend"
application_url = "https://replit.com/@noobequlient/WhatSend.replit.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/api/webhooks/orders-create"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create" ]
  uri = "/api/webhooks/fulfillments-create"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/update" ]
  uri = "/api/webhooks/checkouts-update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products,write_products,read_customers,write_customers,read_orders,write_orders,read_fulfillments,write_fulfillments,read_checkouts,write_checkouts"

[auth]
redirect_urls = [ "https://replit.com/@noobequlient/WhatSend.replit.app/auth/callback" ]