# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "823c4ac0ed0c9aa9aec7a44543fc782e"
name = "WhatSend"
application_url = "https://whatsend-lq9d.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/api/webhooks/orders-create"

  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "/api/webhooks/orders-cancelled"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create" ]
  uri = "/api/webhooks/fulfillments-create"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/update" ]
  uri = "/api/webhooks/checkouts-update"

  [[webhooks.subscriptions]]
  topics = [ "draft_orders/update" ]
  uri = "/api/webhooks/draft-orders-update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products,write_products,read_customers,write_customers,read_orders,write_orders,read_fulfillments,write_fulfillments,read_checkouts,write_checkouts,read_draft_orders"

[auth]
redirect_urls = [ "https://whatsend-lq9d.onrender.com/auth/callback", "https://whatsend-lq9d.onrender.com/api/auth/callback" ]

[pos]
embedded = false
